---
aliases:
  # --------------------
  #   ALIASES: Keys
  # --------------------
  yarn_cache_key: &yarn_cache_key yarn-v1-{{ checksum "yarn.lock" }}

# --------------------
#   COMMANDS
# --------------------
commands:
  build_schema:
    steps:
      - run:
          name: Build schema
          command: |
            yarn build && \
            if [[ `git status --porcelain` ]]; then \
            echo "🚨 Make sure to build the schema after making changes to the definitions."
            exit 1; \
            fi
  run_jest:
    steps:
      - run:
          name: Run Tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
  save_yarn_cache:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: *yarn_cache_key
          paths:
            - ~/.cache/yarn
  restore_yarn_cache:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - *yarn_cache_key
  store_jest_results:
    steps:
      - store_test_results:
          path: ./reports/junit/
  store_jest_artifacts:
    steps:
      - store_artifacts:
          path: ./reports/junit

# --------------------
#   JOBS
# --------------------
version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_yarn_cache
      - install_dependencies
      - save_yarn_cache
      - build_schema
      - run_jest
      - store_jest_results
      - store_jest_artifacts

# --------------------
#   WORKFLOWS
# --------------------
workflows:
  version: 2
  tests:
    jobs:
      - test
