---
type: object
title: Configuration Section Schema of a step
description: |
  The configuration section of a step template holds general options for the
  workflow display.

  Step configurations will override workflow configurations.
additionalProperties: false
properties:
  navigationDelay:
    allOf:
      - $ref: '#/definitions/duration'
      - default: 5s
        description: |
          The duration by which the automatic navigation to the next step is
          delayed.
